README.md
Vegas doesn't require the ``implicit val displayer`` anymore. 
https://github.com/vegas-viz/Vegas/blob/master/notebooks/jupyter_example.ipynb
Updated the Readme to reflect that in the Vegas sample code.
=> Update Vegas sample code.

spark/core/src/main/scala/jupyter/spark/package.scala
Whereas spark 2.0 would log a warning and move on when a duplicated jar was added, in spark 2.1 the behavior now is to throw an exception. See https://github.com/alexarchambault/ammonium/issues/64 for a similar problem.
Since the addJar calls happen in `JupyterSparkSession.builder().getOrCreate()`, it is very hard to recover from this exception in a meaningful way, since there is no way to prevent the addJar calls from happening, or even doing them manually later. Since in my scenario I add many jars, and I cannot predict which ones are duplicate, this is a blocker in my usage of jupter-scala.
I will be happy to polish this change if this solution is acceptable, or to pursue a different path.
=> Do not abort on duplicated jar in spark 2.1.x.

cli/src/main/scala/jupyter/scala/JupyterScala.scala, kernel/src/main/scala/jupyter/scala/Interp.scala
This commit adds the ability for the kernel to take any number of scalac compiler flags given by `--scalac-option -Xopt1 --scalac-option -Yopt2` etc.
It's not very pretty but at least it's possible to do things like enable `-Ypartial-unification`.
=> Take compiler flags using the option `-scalac-option`

jupyter-scala
Without this on `Ubuntu 16.04.2 LTS` and `mktemp (GNU coreutils) 8.25` I get the following error:
```
mktemp: too few X's in template ‘coursier’
```
=> Add `.XXXXXXXX` suffix to `mktemp` command.

spark/core/src/main/scala/jupyter/spark/internals/Spark.scala, spark/core/src/main/scala/jupyter/spark/package.scala
When coursier is caching artifacts from secured repositories, the path looks like
```
~/.coursier/cache/v1/https/<user>%40<repo>/...
```
When such path is added to a spark context directly, it messes up with url encoding and decoding. Internally spark calls `new URI(fileName).getPath` that treats `fileName` as an URL encoded string and decodes it to `.../<user>@<repo>/...` which is not the correct file name.
To overcome this we can convert file name to the `file:` URI `file:/.../<user>%2540<repo>/...` which makes explicit that we want to treat the string as an URL rather than as a file name.
=> Fix authenticated jars access from spark

modules/scala/scala-interpreter/src/main/scala/almond/ScalaInterpreter.scala
Finally figured out why my console was scrolling away every time I tab-completed something.
I'm assuming these were an accidental addition.
=> Delete some debugging println()'s.

modules/scala/scala-kernel-api/src/main/scala/almond/api/Properties.scala, project/Settings.scala
This PR fixes the two following warnings.
- `Adaptation of argument list by inserting () is deprecated: this is unlikely to be what you want.` ([L498](https://travis-ci.org/almond-sh/almond/jobs/446653471#L498))
- `imported `Properties' is permanently hidden by definition of object Properties in package api` ([L550](https://travis-ci.org/almond-sh/almond/jobs/446653471#L550))
=> Fix some warnings

build.sbt, scripts/update-website.sh
Locally, when checking out sources, this makes the version be e.g. `0.1.11-SNAPSHOT` if the latest release is `0.1.10`. This is also used when generating / pushing the website.
=> Tweak snapshot version handling

modules/scala/scala-interpreter/src/main/scala/almond/ScalaInterpreter.scala, modules/scala/scala-kernel-api/src/main/scala/almond/api/helpers/Display.scala, modules/shared/interpreter-api/src/main/scala/almond/interpreter/api/DisplayData.scala
@alexarchambault As discussed this could be generalized and extended in a followup PR to be similar to [IPython.display](
https://ipython.readthedocs.io/en/stable/api/generated/IPython.display.html). But in a more typesafe way.
=> Add basic support for displaying images

project/build.properties
I'm running into the `Different extra API hashes` issue sbt/sbt#4441. Fortunately this has been fixed in sbt 1.2.7.
=> Update to sbt 1.2.7 to get rid of sbt/sbt#4441

modules/scala/scala-interpreter/src/main/scala/almond/ScalaInterpreter.scala, modules/scala/scala-kernel-api/src/main/scala/almond/api/helpers/Display.scala, modules/shared/interpreter-api/src/main/scala/almond/interpreter/api/DisplayData.scala
As discussed @ Scala Spree, these are shortcuts to produce LaTeX and Markdown content from a code cell. The resulting rich text widgets can be updated programatically as well.
This is what you get:
=> Display latex & markdown

modules/scala/scala-interpreter/src/main/scala/almond/ScalaInterpreter.scala, modules/scala/scala-interpreter/src/test/scala/almond/ScalaKernelTests.scala, modules/shared/interpreter/src/main/scala/almond/interpreter/ExecuteResult.scala, modules/shared/interpreter/src/main/scala/almond/interpreter/messagehandlers/InterpreterMessageHandlers.scala, modules/shared/kernel/src/test/scala/almond/kernel/ClientStreams.scala, modules/shared/protocol/src/main/scala/almond/protocol/Execute.scala
As described in #240  typing "exit" in jupyter-console while using the `almond` kernel wouldn't shutdown the kernel. 
This PR solves that issue.
=> Recognize exit keyword in jupyter-console (#240)

modules/scala/scala-interpreter/src/main/scala/almond/ScalaInterpreter.scala, modules/scala/scala-interpreter/src/main/scala/almond/internals/Capture.scala, modules/scala/scala-interpreter/src/main/scala/almond/internals/CaptureImpl.scala, modules/scala/scala-interpreter/src/main/scala/almond/internals/NopCapture.scala, modules/scala/scala-interpreter/src/main/scala/almond/internals/NopOutputStream.scala, modules/scala/scala-interpreter/src/test/scala/almond/ScalaKernelTests.scala, modules/scala/scala-kernel/src/main/scala/almond/Options.scala, modules/scala/scala-kernel/src/main/scala/almond/ScalaKernel.scala, modules/shared/kernel/src/test/scala/almond/kernel/KernelTests.scala
I'd like to automatically run and validate some existings notebooks… This should make their output more reproducible (trapping logs in particular, e.g. like in [this notebook](https://github.com/sbrunk/almond-examples/blob/e3bc675b60dfde2b24d1345713752d94ecc92e58/tensorflow_scala.ipynb)).
=> Allow to trap what user code sends to stdout / stderr

modules/scala/scala-kernel/src/main/scala/almond/Options.scala, modules/scala/scala-kernel/src/main/scala/almond/ScalaKernel.scala
So that this doesn't rely on specific methods being called by reflection on parent classloaders. Plus the method this tries to find should go away in the coursier bootstraps.
=> Simplify base classloader lookup

build.sbt, docs/pages/dev-from-sources.md, project/plugins.sbt
```bash
$ sbt jupyterStart shell
```
is enough to spawn a jupyter lab server with a source-based kernel.
Typing
```
> ~scala-kernel/pack
```
watches the sources and re-generates the kernel upon changes. Just re-starting the kernel from the Jupyter UI then picks the new kernel.
=> Add sbt-pack-based from sources setup

modules/shared/channels/src/main/scala/almond/channels/zeromq/ZeromqSocketImpl.scala, modules/shared/channels/src/test/scala/almond/channels/zeromq/ZeromqSocketTests.scala
When running kernels on Google Colaboratory, the `key` value in `connection.json` is empty to indicate that authentication and signature checking should be disabled (noted in the [official docs](https://jupyter-client.readthedocs.io/en/stable/messaging.html#wire-protocol)). This PR updates `ZeromqSocketImpl` to handle the situation where `key` is empty by using an empty string as the signature when sending a message and skipping the signature check when receiving a message. With these changes, Almond works perfectly inside Colaboratory.
=> Handle connection key being empty to support Google Colaboratory

scripts/install-kernels.sh, scripts/update-docker-images.sh
cc @sbrunk 
I tested that a bit in a `debug` branch ([Travis CI job](https://travis-ci.org/almond-sh/almond/jobs/512087588), it already pushed its image, run it with `docker run -it --rm -p 8888:8888 almondsh/almond:snapshot`).
=> Tweak docker scripts

modules/scala/jupyter-api/src/main/scala/almond/display/Image.scala
Includes `BufferedImage` (which implements `RenderedImage`) as done back in #35.
Usage example with [EvilPlot](https://cibotech.github.io/evilplot/) (or as [gist](https://gist.github.com/sbrunk/021a0a089e31e6dbbc66f25ef8a86ce1)):
```scala
interp.repositories() ++= Seq(
coursier.MavenRepository("https://dl.bintray.com/cibotech/public")
)
```
```scala
import $ivy.`com.cibo::evilplot-repl:0.6.3`
import com.cibo.evilplot.plot._
import com.cibo.evilplot.plot.aesthetics.DefaultTheme._
import com.cibo.evilplot.numeric.Point
val data = Seq.tabulate(100) { i =>
Point(i.toDouble, scala.util.Random.nextDouble())
}
val plot = ScatterPlot(data)
.xAxis()
.yAxis()
.frame()
.xLabel("x")
.yLabel("y")
.render()
Image.fromRenderedImage(plot.asBufferedImage, Image.PNG)
```
=> Add support for java.awt.image.RenderedImage

modules/scala/almond-spark/src/main/scala/org/apache/spark/sql/almondinternals/SendLog.scala, modules/shared/interpreter-api/src/main/scala/almond/interpreter/api/CommHandler.scala, modules/shared/interpreter/src/main/scala/almond/interpreter/comm/DefaultCommHandler.scala, modules/shared/interpreter/src/test/scala/almond/interpreter/TestInterpreter.scala, project/Mima.scala, project/Settings.scala
ipywidgets sets its protocol version in the metadata of the comm messages it sends.
This is an attempt to support setting metadata for comm messages. Sending comm messages also throws exceptions now if data or metadata can't be parsed into JSON objects (it was a TODO before in `DefaultCommHandler`).
=> Comm Enhancements

Dockerfile, scripts/update-docker-images.sh
Rather than jupyter/minimal-notebook, which adds around 2 GB.
=> Use jupyter/base-notebook as base docker image

modules/shared/protocol/src/main/scala/almond/protocol/KernelInfo.scala
This should solve the syntax highlighting issues described in #398.
=> Add ok status to KernelInfo replies. Fixes #398

.travis.yml
This should help with #444 as travis uses an older non BuildKit based Docker daemon by default that can't skip executing unused build stages.
=> Use a more recent Docker daemon in travis

modules/scala/jupyter-api/src/main/scala/almond/api/JupyterApi.scala, modules/scala/scala-interpreter/src/main/scala/almond/Execute.scala, modules/scala/scala-interpreter/src/main/scala/almond/JupyterApiImpl.scala, modules/scala/scala-interpreter/src/main/scala/almond/ScalaInterpreter.scala, modules/scala/scala-interpreter/src/test/scala/almond/ScalaInterpreterTests.scala
=> Allow silencing of REPL output from Jupyter API

build.sbt
Should make the Sonatype checks happy (upon release).
=> Publish dummy javadoc for modules using jsoniter-scala macros

.vscode/settings.json
Should make importing almond in vscode  work out-of-the-box.
=> Use custom sbt launcher via workspace settings

docs/website/siteConfig.js
👋 team,
I am working on DocSearch. [We have an integration for Docusaurus](https://docusaurus.io/docs/en/search#enabling-the-search-bar). We thought it is a shame you can not also used this search that you can [find on reactjs for example](https://reactjs.org/).
This PR will add DocSearch to the documentation website. It will allow an user to have a learn-as-you-type experience by displaying results thanks to a dropdown in a live way.
Let me know if you need anything.
=> feat(website): add DocSearch as recommended by docusaurus

.vscode/settings.json, project/Settings.scala, project/plugins.sbt
This also allows to use vanilla sbt launchers.
=> Don't require sbt-coursier anymore

docs/pages/dev-from-sources.md, docs/pages/install-multiple.md, docs/pages/install-other.md, docs/pages/quick-start-install.md
This considerably simplifies the coursier command starting almond.
=> Use almond from coursier apps in the installation instructions

modules/shared/kernel/src/main/scala/almond/kernel/install/Install.scala
So that it has sensible permissions by default.
=> Write launcher.jar as a new file rather than via Files.copy

build.sbt, modules/scala/scala-kernel-api/src/main/scala/almond/api/Properties.scala, modules/scala/scala-kernel/src/main/scala/almond/Options.scala, modules/scala/scala-kernel/src/main/scala/almond/ScalaKernel.scala, modules/scala/scala-kernel/src/main/scala/almond/Scalafmt.scala, modules/scala/scala-kernel/src/test/scala/almond/ScalafmtTests.scala, modules/shared/kernel/src/main/scala/almond/kernel/Kernel.scala, modules/shared/protocol/src/main/scala/almond/protocol/custom/Format.scala, project/Deps.scala, project/Settings.scala
This adds handlers for `format_request` messages, sent by the [`@almond-sh/scalafmt` extension](https://github.com/almond-sh/almond-scalafmt), allowing one to format one or all cells in almond notebooks from JupyterLab.
~Not tested against the [published version](https://www.npmjs.com/package/@almond-sh/scalafmt) of `@almond-sh/scalafmt` yet.~
=> scalafmt support

modules/scala/scala-kernel/src/main/scala/almond/ScalaKernel.scala, modules/shared/kernel/src/main/scala/almond/kernel/install/Install.scala, modules/shared/kernel/src/main/scala/almond/kernel/install/Options.scala
This adds a `--env` option, that allows to specify environment variables to be set via the kernel spec of the kernel. Use like
```text
$ cs launch almond -- --install --env JAVA_OPTS=-Xmx3g --env FOO=bar
```
This example adds an `env` field in the [kernel spec](https://jupyter-client.readthedocs.io/en/stable/kernels.html#kernel-specs) of the kernel that is being installed, with value `{ "JAVA_OPTS": "-Xmx3g", "FOO": "bar" }`.
=> Allow to specify env vars to be set via the kernel spec

build.sbt, modules/scala/almond-spark/src/main/scala/org/apache/spark/sql/almondinternals/ProgressSparkListener.scala
Spark progress bar front end's updates and polled once a second instead of pushed by each task start/end.
Should fix #448 
Tested using
```
spark.range(10000000).repartition(5000).count
```
Works both locally and on a cluster with typical spark jobs.
=> Use async polling to update the front-end for spark progress bar

docs/pages/try-deepnote.md, docs/website/sidebars.json
Hi, Deepnote just added a possibility to install custom environments and also documented usage with Almond. I'd say it's a pretty good addition to Binder and NBviewer ;)
Disclaimer: I am a core member of Deepnote team.
=> Add Deepnote to Try it section in the Docs

modules/scala/scala-interpreter/src/main/scala/almond/amm/AlmondPreprocessor.scala, modules/scala/scala-interpreter/src/test/scala/almond/ScalaInterpreterTests.scala
This fix the error occurs when running any import statement with variable inspector enabled.
```scala
import scala.util.Properties
```
```
cmd0.sc:7: not found: value res0
.declareVariable("res0", res0); Iterator() },
^Compilation Failed
Compilation Failed
```
=> Fix import error

modules/scala/scala-interpreter/src/main/scala/almond/amm/AlmondPreprocessor.scala, modules/shared/protocol/src/main/scala/almond/protocol/Complete.scala, modules/shared/protocol/src/test/scala/almond/protocol/ProtocolTests.scala
Fix the issue when doing completion and there are no matches, the `matches` field is omitted from the reply message during json serialization, so for example returns
```json
{"cursor_start":7,"cursor_end":7,"metadata":{},"status":"ok"}
```
instead of the correct
```json
{"matches":[],"cursor_start":7,"cursor_end":7,"metadata":{},"status":"ok"}
```
Discovered when I was using jupyter console, might cause problems with other jupyter clients as well.
On an unrelated note, also add the white space I missed in my previous PR. Doesn't affect anything, but kinda trips me a little bit once I've noticed it...
=> Prevent omitting empty `matches` field from `complete_reply` during json serialization

build.sc
Without this, I'm getting
```
scala.scala-kernel[2.12.16].finalMainClass No main class specified or found
```
when running
```
$ ./mill -i 'scala.scala-kernel[2.12.16].launcher'
```
=> Add missing explicit main class

modules/scala/scala-interpreter/src/main/java/almond/internals/AnsiToHtmlProcessor.java, modules/scala/scala-interpreter/src/main/java/almond/internals/HtmlAnsiOutputStream.java, project/deps.sc
Almond uses jansi's `HtmlAnsiOutputStream` to convert the ammonite's output (ansi) to Jupyter output (HTML)
However, jansi dropped HtmlAnsiOutputStream support (at least from 2.0.0), and the API of AnsiOutputStream has quite changed. see: https://github.com/fusesource/jansi/issues/210
This commit adopt the jansi v2 compatible HtmlAnsiOutputStream implementation from https://github.com/fusesource/jansi/pull/212 Even though the PR isn't merged because the maintainer doesn't believe there's no demand on HtmlAnsiOutputStream, but the code seems legit, and I believe we can safe to use that implementation.
=> Bump jansi to 2.4.0

docs/pages/install-options.md, modules/scala/scala-interpreter/src/main/scala/almond/Execute.scala, modules/scala/scala-interpreter/src/main/scala/almond/ScalaInterpreter.scala, modules/scala/scala-interpreter/src/main/scala/almond/ScalaInterpreterParams.scala, modules/scala/scala-kernel/src/main/scala/almond/Options.scala, modules/scala/scala-kernel/src/main/scala/almond/ScalaKernel.scala
- Added new boolean option '--use-thread-interrupt' for allowing kernel to be interrupted using 'Thread.interrupt' method rather than deprecated 'Thread.stop' method. For backward compatibility, default value of this option is 'false', i.e. 'Thread.stop' is used when option is not specified or set to 'false'
- Added entry in documentation for new option
- Ran test suite to ensure default interrupt behavior of kernel is preserved
=> Add New Option '--use-thread-interrupt'

modules/scala/scala-interpreter/src/test/scala/almond/ScalaKernelTests.scala, modules/scala/toree-hooks/src/main/scala/almond/toree/LineMagicHandlers.scala
`import $cp` would be better, as it ensures the class path is updated prior to compiling and running the current cell. But we need com-lihaoyi/Ammonite#1340 to make it work.
=> Temporarily rely on interp.load.cp to back %AddJar

.github/workflows/ci.yml
=> Run non-Java 8 job on Java 17 on CI

.gitpod.Dockerfile, Dockerfile, docs/pages/dev-from-sources.md, docs/pages/install-multiple.md
These are commits from https://github.com/almond-sh/almond/pull/779 / https://github.com/almond-sh/almond/pull/1110 that aren't really related to inspections
=> Some doc updates

docs/pages/dev-from-sources.md
Looks like the section on generating Metals and IntelliJ files was duplicated due to merging. Also fixed the link to Mill doc.
=> Remove duplicated IDE setup doc

modules/shared/interpreter/src/main/scala/almond/interpreter/messagehandlers/MessageHandler.scala, modules/shared/kernel/src/main/scala/almond/kernel/Kernel.scala, modules/shared/test-kit/src/main/scala/almond/testkit/ClientStreams.scala
It doesn't really make sense for us to bound queues here… they all get filled after actions users manually took (like doing "Run all cells" in a notebook with x hundreds cells…), so we can't really get flooded and crash because of that - we're not a web service treating 1000s of req / s…
Doing this to address a possible deadlock I've been seeing with the new launcher, with a "Run all cells" in a large notebook (> 50 cells, former size of most bounded queues in Almond) deadlocking things.
=> Unbound most queues

modules/scala/scala-interpreter/src/main/scala/almond/Execute.scala, modules/scala/scala-interpreter/src/test/scala/almond/ScalaInterpreterTests.scala, modules/scala/scala-interpreter/src/test/scala/almond/ScalaKernelTests.scala, modules/shared/interpreter/src/main/scala/almond/interpreter/ExecuteResult.scala, modules/shared/interpreter/src/main/scala/almond/interpreter/messagehandlers/InterpreterMessageHandlers.scala, modules/shared/test-kit/src/main/scala/almond/testkit/ClientStreams.scala
Current code constructs Execute.error (which is then translated to ExecuteReply.error) by setting `ename="", stackTrace=Nil, evalue=<the whole exception as a string>`. While this is rendered correctly in Jupyter(Lab), it feels like a semantical violation of Jupyter messaging protocol. This PR aims to fix that.
Please let me know if `ename` and `stackTrace` fields were left blank intentionally! 
- additional checks in `ScalaInterpreterTests` verifying `ename` and `stackTrace` fields of `ExecuteReply.Error` message
- additional checks in `ScalaKernelTests` verifying `ename` and `stackTrace` fields of `Execute.Error` message
- manually verified that JupyterLab displays errors identically with and without this change and that my changes could be observed in a browser WS channel. 
Before …
=> Set proper fields in ExecuteReply.Error and Execute.error

docs/pages/api-jupyter.md, modules/scala/scala-interpreter/src/main/scala/almond/JupyterApiImpl.scala, modules/scala/scala-interpreter/src/main/scala/almond/ScalaInterpreter.scala
- Added support for post-interrupts hooks to e.g. allow remote jobs kicked off from a Jupyter notebook cell to be interrupted when the cell itself is interrupted
- An example was added to 'api-jupyter.md' to demonstrate how to add a post-interrupt hook in PREDEFS code of an Almond based kernel for stopping Spark jobs
=> Add Support for Post-interrupt Hooks

modules/shared/kernel/src/main/scala/almond/kernel/Kernel.scala
Seems the handover from the first launcher to the main one sometimes loses messages when starting the kernel takes longer than this duration…
=> Increase zeromq linger period

docs/pages/api-jupyter.md, modules/scala/jupyter-api/src/main/scala/almond/api/JupyterApi.scala, modules/scala/scala-interpreter/src/main/scala/almond/Execute.scala, modules/scala/scala-interpreter/src/main/scala/almond/JupyterApiImpl.scala, modules/scala/scala-interpreter/src/main/scala/almond/ScalaInterpreter.scala
This is a rework of https://github.com/almond-sh/almond/pull/1186 to make the post-interrupt hook feature work as intended:
- Added abstract functions to ‘JupyterApi.scala’ to make interface visible to Ammonite kernel object
- Added API usage examples to ‘api-jupyter.md’
- Added convenience functions for facilitating JupyterApi instance access,
since it is hard to pass around through function/method calls. In case at
hand, we need to access it from methods ‘interruptible’ and ‘interrupt’ in
class ‘Execute’
- Added a label field to each registered hook, since Scala lambda functions
are not easy to print in human readable form
- Did local testing of API  both when sending interrupt messages via SIGINT or via 
zeromq message, i.e. without/with '--interrupt-via-message’)
Note: Contrary to …
=> Add Fixes for Post-Interrupt Hook Feature

modules/scala/scala-interpreter/src/main/scala/almond/Execute.scala, modules/scala/scala-interpreter/src/main/scala/almond/ScalaInterpreter.scala, modules/scala/scala-interpreter/src/main/scala/almond/ScalaInterpreterParams.scala, modules/scala/scala-interpreter/src/main/scala/almond/internals/Capture.scala, modules/scala/scala-interpreter/src/main/scala/almond/internals/CaptureImpl.scala, modules/scala/scala-interpreter/src/test/scala/almond/ScalaKernelTests.scala, modules/scala/scala-kernel/src/main/scala/almond/Options.scala, modules/scala/scala-kernel/src/main/scala/almond/ScalaKernel.scala, modules/scala/test-definitions/src/main/scala/almond/integration/Tests.scala
This PR introduces a new `quiet` interpreter parameter which controls mirroring stdout/stderr to console. This is similar to IPKernelApp.quiet parameter. It could be used to collect kernel's output and store it somewhere to make debugging things easier.
Another possible option to support this is to change the existing `trapOutput` flag from `Boolean` to `String` to support three modes: `trap`, `mirror`, `default`, but this would be a breaking change. I'm happy to go with that approach if you think that it's better to keep amount of flags low and you don't care that much about changing parameter name/type
Manually with jupyterlab
New tests which capture console output and verify it
=> Add "quiet" interpreter param which controls mirroring stdout/stderr to console

.github/workflows/ci.yml
Seems the new macos-14 images are on ARM64, which has no Java 8. We can think later about updating the JVM in the tests.
=> Stay on macos-12 for now

modules/scala/integration/src/test/scala/almond/integration/KernelTestsTwoStepStartup213.scala, modules/scala/scala-interpreter/src/main/scala/almond/amm/AmmInterpreter.scala, modules/scala/scala-kernel/src/test/scala/almond/ScalafmtTests.scala, modules/scala/test-definitions/src/main/scala/almond/integration/Tests.scala
This is the name expected by Spark.
=> revert to cmd for the wrapper name

project/deps.sc
Quite old versions, plus they crash 'shared.test-kit[…].compile' on JDK 21 or other compilation tasks
=> Drop support for 2.12.{16,17}, 2.13.10, and 3.3.0

project/deps.sc
Newer versions of Metals don't support it
=> Drop Scala 2.13.11 support

build.sc
Not sure why we were doing this… This is a problem when building Almond with newer JDKs that this Scala version doesn't support
=> Stop compiling shared-directives modules with 2.12.15

modules/echo/src/main/scala/almond/echo/EchoKernel.scala, modules/echo/src/main/scala/almond/echo/Options.scala, modules/scala/integration/src/main/scala/almond/integration/KernelLauncher.scala, modules/scala/launcher/src/main/scala/almond/launcher/Launcher.scala, modules/scala/launcher/src/main/scala/almond/launcher/LauncherOptions.scala, modules/scala/scala-kernel/src/main/scala/almond/Options.scala, modules/scala/scala-kernel/src/main/scala/almond/ScalaKernel.scala, modules/shared/channels/src/main/scala/almond/channels/Connection.scala, modules/shared/channels/src/main/scala/almond/channels/ConnectionParameters.scala, modules/shared/channels/src/main/scala/almond/channels/zeromq/ZeromqConnection.scala, modules/shared/channels/src/main/scala/almond/channels/zeromq/ZeromqSocket.scala, modules/shared/channels/src/main/scala/almond/channels/zeromq/ZeromqSocketImpl.scala, modules/shared/channels/src/test/scala/almond/channels/zeromq/ZeromqConnectionTests.scala, modules/shared/channels/src/test/scala/almond/channels/zeromq/ZeromqSocketTests.scala, modules/shared/kernel/src/main/scala/almond/kernel/Kernel.scala
This adds a `--bind-to-random-ports` option, which is enabled by default (can be disabled with `--bind-to-random-ports=false`). This option makes Almond accept connection files with one or more ports set to `0`. When that's the case, Almond asks zeromq to pick a random port to bind to, which works around race conditions where: Jupyter, or the app launching the kernel, picks random available ports, passes them to Almond in a connection file, and another concurrent app uses those port before Almond binds to them.
Connection files with ports set to `0` are then used by default in the integration tests here, to ensure it all works.
Fixes https://github.com/almond-sh/almond/issues/1502
=> Add ability to bind to random ports

modules/scala/launcher/src/main/scala/almond/launcher/LauncherOutputHandler.scala, modules/scala/scala-interpreter/src/main/scala/almond/Execute.scala, modules/scala/scala-interpreter/src/test/scala/almond/MockOutputHandler.scala, modules/scala/scala-interpreter/src/test/scala/almond/ScalaKernelTests.scala, modules/shared/interpreter-api/src/main/scala/almond/interpreter/api/OutputHandler.scala, modules/shared/interpreter/src/main/scala/almond/interpreter/messagehandlers/InterpreterMessageHandlers.scala, modules/shared/protocol/src/main/scala/almond/protocol/Execute.scala, modules/shared/test-kit/src/main/scala/almond/testkit/ClientStreams.scala, modules/shared/test/src/main/scala/almond/interpreter/TestOutputHandler.scala
This allows users to add "payloads" to execute reply (both successful ones and errors), like
```scala
publish.addPayload("""{"source": "foo", "thing": 2}""")
```
`addPayload` expects a stringified JSON object. The payload is then assumed to be a JSON object, and written in the `payloads` field of [`execute_reply`](https://jupyter-client.readthedocs.io/en/5.2.3/messaging.html#execution-results) message. Note that unlike what the spec says, we also add the `payloads` field in errored `execute_reply`, like ipykernel apparently does.
---
Backport of https://github.com/almond-sh/almond/pull/1562
=> Allow users to add payloads to execute reply messages (0.14.1)
