almond-sh/almond

kernel/src/main/scala/jupyter/scala/ScalaInterpreter.scala
I think this fixes #26 and #31
=> just replaced scala with .scala in the interpreter settings

modules/scala/scala-interpreter/src/test/scala/almond/ScalaInterpreterTests.scala, project/Deps.scala
Includes https://github.com/lihaoyi/Ammonite/pull/853 in particular, which makes running several cells in a row feel much faster here.
=> Switch to latest Ammonite snapshot

.gitignore
- .DS_Store (macOS Finder)
- .idea (IntelliJ IDEA)
=> Some helpful .gitignore's

modules/shared/interpreter/src/main/scala/almond/interpreter/IOInterpreter.scala, modules/shared/interpreter/src/main/scala/almond/interpreter/Interpreter.scala, modules/shared/interpreter/src/main/scala/almond/interpreter/InterpreterToIOInterpreter.scala, modules/shared/interpreter/src/main/scala/almond/interpreter/messagehandlers/InterpreterMessageHandlers.scala, modules/shared/interpreter/src/main/scala/almond/interpreter/messagehandlers/MessageHandler.scala, modules/shared/kernel/src/main/scala/almond/kernel/Kernel.scala, modules/shared/kernel/src/test/scala/almond/kernel/KernelTests.scala, modules/shared/kernel/src/test/scala/almond/kernel/TestInterpreter.scala, modules/shared/protocol/src/main/scala/almond/protocol/Shutdown.scala
Fixes #220.
Disclaimer: This is my first time working w/ cats/fs2. There are likely some subtleties involved in sleeping before shutdown that I've missed.
=> Handle shutdown messages.

modules/scala/scala-interpreter/src/main/scala/almond/internals/UpdatableResults.scala, modules/scala/scala-interpreter/src/test/scala/almond/UpdatableResultsTests.scala
Fixes https://github.com/almond-sh/almond/issues/216.
=> Tweak updatable results handling

.travis.yml, modules/scala/scala-interpreter/src/main/scala/almond/ScalaInterpreter.scala, modules/scala/scala-interpreter/src/test/scala/almond/ScalaInterpreterTests.scala, modules/scala/scala-kernel/src/main/scala/almond/ScalaKernel.scala, project/Deps.scala, project/Settings.scala, scripts/generate-website.sh
~Needs mdoc release with https://github.com/olafurpg/mdoc/pull/107.~
=> Add scala 2.12.8 support

modules/scala/scala-interpreter/src/main/scala/almond/ScalaInterpreter.scala, modules/scala/scala-interpreter/src/main/scala/almond/internals/CancellableFuturePool.scala
Fixes https://github.com/almond-sh/almond/issues/241.
=> Asynchronously run completions / inspections in scala kernel

project/Deps.scala
(And the latest ammonite-spark, that switched to it too.)
=> Switch to ammonite 1.5.0

modules/scala/scala-interpreter/src/main/scala/almond/ScalaInterpreter.scala, modules/scala/scala-kernel-api/src/main/scala/almond/api/helpers/Display.scala
And make them deterministic if the right Java property is set.
=> Add helpers to get random ids

build.sbt, modules/scala/scala-interpreter/src/main/scala/almond/ScalaInterpreter.scala, modules/scala/scala-kernel/src/main/scala/almond/Options.scala, modules/scala/scala-kernel/src/main/scala/almond/ScalaKernel.scala, project/Deps.scala
#303
The cache seems to work, but I'm not sure if storing in `~/.almond` is appropriate.
=> Use compilation cache

docs/pages/usage-spark.md
We should automate that in the future (either the module version itself or the version in the docs).
=> Update almond-spark dependency

examples/plotly-scala.ipynb, modules/scala/scala-interpreter/src/main/scala/almond/amm/AmmInterpreter.scala, project/Deps.scala
(Needs ammonite-spark [`0.4.2`](https://github.com/alexarchambault/ammonite-spark/releases/tag/v0.4.2) to be synced to Central.)
=> Switch to Ammonite 1.6.7

modules/scala/scala-interpreter/src/main/java/almond/internals/HtmlAnsiOutputStream.java, modules/scala/scala-interpreter/src/main/scala/almond/Execute.scala, modules/scala/scala-kernel-api/src/main/scala/almond/display/PrettyPrint.scala
For things to look better in nteract in particular.
=> Tweak updated display style

build.sbt, modules/scala/almond-rx/src/main/scala-2.11/almondrx/internals/Compat.scala, modules/scala/almond-rx/src/main/scala-2.12_2.13/almondrx/internals/Compat.scala, modules/scala/almond-rx/src/main/scala/almondrx/package.scala, modules/scala/almond-spark/src/main/scala/org/apache/spark/sql/NotebookSparkSession.scala, modules/scala/almond-spark/src/main/scala/org/apache/spark/sql/almondinternals/NotebookSparkSessionBuilder.scala, modules/scala/scala-interpreter/src/main/scala-2.11/almond/internals/AmmCompat.scala, modules/scala/scala-interpreter/src/main/scala-2.11_2.12/almond/internals/ScalaInterpreterInspections.scala, modules/scala/scala-interpreter/src/main/scala-2.12_2.13/almond/internals/AmmCompat.scala, modules/scala/scala-interpreter/src/main/scala-2.13/almond/internals/ScalaInterpreterInspections.scala, modules/scala/scala-interpreter/src/main/scala/almond/Execute.scala, modules/scala/scala-interpreter/src/main/scala/almond/ReplApiImpl.scala, modules/scala/scala-interpreter/src/main/scala/almond/ScalaInterpreter.scala, modules/scala/scala-interpreter/src/main/scala/almond/amm/AmmInterpreter.scala, modules/scala/scala-interpreter/src/main/scala/almond/internals/UpdatableFuture.scala, modules/scala/scala-kernel-api/src/main/scala-2.11/almond/display/PrettyPrintHelper.scala, modules/scala/scala-kernel-api/src/main/scala-2.11/ammonite/interp/api/APIHolder.scala, modules/scala/scala-kernel-api/src/main/scala-2.12_2.13/almond/display/PrettyPrintHelper.scala, modules/scala/scala-kernel-api/src/main/scala/almond/api/JupyterAPIHolder.scala, modules/scala/scala-kernel-api/src/main/scala/almond/display/PrettyPrint.scala, project/Deps.scala, project/Settings.scala
~Needs https://github.com/alexarchambault/ammonite-spark/pull/50.~
=> Bump Ammonite

docs/pages/api.md, docs/pages/dev-website.md, docs/website/pages/en/index.js
and fix a few links.
@alexarchambault when you're looking at this perhaps you could also add the logo to the almond-sh GitHub org?
=> Update instructions for building the website

appveyor.yml
Seems the current latest coursier CLI has some regressions…
=> Fix coursier CLI version on Appveyor

appveyor.yml
Ensure the scala version isn't unexpectedly bumped in particular.
Should make https://github.com/almond-sh/almond/pull/432 pass.
=> Tweak example validation on Appveyor

modules/scala/scala-interpreter/src/main/scala/almond/ReplApiImpl.scala
Fixes NPE in ReplApiImpl.printSpecial in issue #475.
=> Fix NullPointerException in ReplApiImpl.printSpecial

docs/pages/quick-start-install.md
Put information from #299 in the docs.
=> Document how to update almond kernel

docs/pages/quick-start-install.md
Put information from almond-sh#161 in the docs. Replaces #480.
=> Document how to unistall almond kernel

docs/pages/install-versions.md
Put information from #300 in the docs.
=> Document how to find out almond version

modules/shared/channels/src/main/scala/almond/channels/zeromq/ZeromqConnection.scala
Was getting weird errors about it, when using almond from the latest vscode-python. These errors went away with these changes.
=> Tweak heartbeat handling

modules/shared/protocol/src/main/scala/almond/protocol/Protocol.scala
Fixes https://github.com/almond-sh/almond/issues/626.
=> Bump jupyter protocol version to 5.4

examples/colors.ipynb, modules/scala/scala-interpreter/src/main/scala/almond/amm/AmmInterpreter.scala, modules/scala/scala-interpreter/src/main/scala/almond/internals/UpdatableFuture.scala
Fixes https://github.com/almond-sh/almond/issues/635.
=> Fix colors handling

README.md
This reverts commit 09b4f0080ab0454ed31720ae380219be123367a4.
=> Revert "Mention GSoC in README (#771)"

docs/website/package-lock.json
Running the website locally seems to work, and updated things to this
=> Update website package-lock.json

.github/workflows/ci.yml, .mill-jvm-opts, build.sc, modules/scala/integration/src/test/scala/almond/integration/KernelLauncher.scala, modules/scala/integration/src/test/scala/almond/integration/KernelTests.scala, modules/scala/scala-interpreter/src/main/scala-2/almond/internals/ScalaInterpreterInspections.scala, modules/scala/scala-interpreter/src/test/scala/almond/ScalaKernelTests.scala, modules/scala/test-definitions/src/main/scala/almond/integration/Tests.scala, modules/scala/toree-hooks/src/main/scala/almond/toree/LineMagicHandlers.scala, modules/shared/channels/src/main/scala/almond/channels/ConnectionParameters.scala, modules/shared/channels/src/test/scala/almond/channels/zeromq/ZeromqSocketTests.scala, modules/shared/test-kit/src/main/scala/almond/testkit/Dsl.scala, project/deps.sc, project/settings.sc
Bumping Ammonite brings a better `import $cp` (via https://github.com/com-lihaoyi/Ammonite/pull/1340), which we can use to make `%AddJar` better (allow code to refer to classes brought by an `%AddJar` in the same cell)
=> Bump Ammonite, tweak Toree magic %AddJar

build.sc, modules/echo/src/main/scala/almond/echo/EchoKernel.scala, modules/scala/integration/src/test/scala/almond/integration/KernelLauncher.scala, modules/scala/scala-interpreter/src/main/scala/almond/Execute.scala, modules/scala/scala-interpreter/src/main/scala/almond/ScalaInterpreter.scala, modules/scala/scala-interpreter/src/main/scala/almond/ScalaInterpreterParams.scala, modules/scala/scala-interpreter/src/test/scala/almond/ScalaKernelTests.scala, modules/scala/scala-interpreter/src/test/scala/almond/TestUtil.scala, modules/scala/scala-kernel/src/main/scala/almond/Options.scala, modules/scala/scala-kernel/src/main/scala/almond/ScalaKernel.scala, modules/scala/test-definitions/src/main/scala/almond/integration/Tests.scala, modules/shared/channels/src/main/scala/almond/channels/Channel.scala, modules/shared/channels/src/main/scala/almond/channels/zeromq/ZeromqSocketImpl.scala, modules/shared/interpreter/src/main/scala/almond/interpreter/ExecuteResult.scala, modules/shared/interpreter/src/main/scala/almond/interpreter/Message.scala, modules/shared/interpreter/src/main/scala/almond/interpreter/messagehandlers/CloseExecutionException.scala, modules/shared/interpreter/src/main/scala/almond/interpreter/messagehandlers/InterpreterMessageHandlers.scala, modules/shared/interpreter/src/main/scala/almond/interpreter/messagehandlers/MessageHandler.scala, modules/shared/kernel/src/main/scala/almond/kernel/Kernel.scala, modules/shared/kernel/src/main/scala/almond/kernel/MessageFile.scala, modules/shared/kernel/src/test/scala/almond/kernel/KernelTests.scala, modules/shared/test-kit/src/main/scala/almond/testkit/Dsl.scala, project/settings.sc
See https://github.com/almond-sh/almond/pull/1124
=> Preliminary developments for two-step startup

.github/workflows/ci.yml, .github/workflows/release.yml, build.sc, modules/echo/src/main/scala/almond/echo/Options.scala, modules/scala/scala-interpreter/src/main/scala/almond/ScalaInterpreter.scala, modules/scala/scala-interpreter/src/main/scala/almond/amm/AmmInterpreter.scala, modules/scala/scala-kernel/src/main/scala/almond/Options.scala, modules/shared/kernel/src/main/scala/almond/kernel/MessageFile.scala, project/settings.sc, scripts/website0/Website.sc
These are commits from https://github.com/almond-sh/almond/pull/1239 that are not tied to the Mill version bump
=> Various minor things

.github/workflows/ci.yml, .github/workflows/release.yml, modules/scala/scala-interpreter/src/main/scala/almond/Execute.scala, project/settings.sc
But keep publishing Java 8 compatible artifacts
=> Use JDK 21 on CI

modules/scala/integration/src/main/scala/almond/integration/KernelTestsDefinitions.scala, modules/scala/scala-interpreter/src/test/scala/almond/ScalaKernelTests.scala, modules/scala/test-definitions/src/main/scala/almond/integration/Tests.scala
These are closer to the way Almond is run in practice
=> Run exception handlers tests via ITs too

build.mill, examples/plotly-scala.ipynb, mill-build/src/almondbuild/Deps.scala, modules/scala/examples/src/test/scala/almond/examples/Examples.scala, modules/scala/scala-interpreter/src/main/scala-2/almond/internals/ScalaInterpreterInspections.scala, modules/scala/scala-interpreter/src/test/scala/almond/ScalaInterpreterTests.scala, modules/scala/scala-interpreter/src/test/scala/almond/ScalaKernelTests.scala, modules/scala/scala-interpreter/src/test/scala/almond/TestUtil.scala, modules/scala/test-definitions/src/main/scala/almond/integration/Tests.scala
Bits from https://github.com/almond-sh/almond/pull/1543 that shouldn't break the CI
=> Prepare for Mill 1.0
